version: '3.8'
services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      # Add any required environment variables here, e.g. EXA_API_KEY
    command: ["node", "build/index.js"]
